[package]
name = "zhc"
description = "ZHC: Top-level"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish = true

[dependencies]
zhc_ir.workspace = true
zhc_crypto.workspace = true
zhc_sim.workspace = true
zhc_utils.workspace = true
zhc_langs.workspace = true
zhc_builder.workspace = true
zhc_pipeline.workspace = true
zhc_config.workspace = true

[[example]]
name = "profile_pipeline"
path = "examples/profile_pipeline.rs"
