[package]
name = "zhc_langs"
description = "ZHC: Dialects registry"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish = true

[dependencies]
zhc_ir.workspace = true
zhc_langs_macro.workspace = true
zhc_utils.workspace = true
zhc_crypto.workspace = true
serde.workspace = true
