[package]
name = "zhc_pipeline"
description = "ZHC: Compilation pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
zhc_ir.workspace = true
zhc_sim.workspace = true
zhc_utils.workspace = true
zhc_langs.workspace = true
zhc_crypto.workspace = true
zhc_config.workspace = true
zhc_profiling.workspace = true
serde.workspace = true
bitfield-struct.workspace = true
rand.workspace = true
