use hpuc_ir::ValId;

/// A handle to a 1-LUT in the IR.
#[derive(Clone, Copy)]
pub struct Lut(pub ValId);

/// A handle to 2-LUT in the IR.
#[derive(Clone, Copy)]
pub struct Lut2(pub ValId);

/// Enumeration of all available LUT1 types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Lut1Type {
    None,
    MsgOnly,
    CarryOnly,
    CarryInMsg,
    MultCarryMsg,
    MultCarryMsgLsb,
    MultCarryMsgMsb,
    BwAnd,
    BwOr,
    BwXor,
    CmpSign,
    CmpReduce,
    CmpGt,
    CmpGte,
    CmpLt,
    CmpLte,
    CmpEq,
    CmpNeq,
    ReduceCarry2,
    ReduceCarry3,
    ReduceCarryPad,
    GenPropAdd,
    IfTrueZeroed,
    IfFalseZeroed,
    Ripple2GenProp,
    CmpGtMrg,
    CmpGteMrg,
    CmpLtMrg,
    CmpLteMrg,
    CmpEqMrg,
    CmpNeqMrg,
    IsSome,
    CarryIsSome,
    CarryIsNone,
    MultCarryMsgIsSome,
    MultCarryMsgMsbIsSome,
    IsNull,
    IsNullPos1,
    NotNull,
    MsgNotNull,
    MsgNotNullPos1,
    SolvePropGroupFinal0,
    SolvePropGroupFinal1,
    SolvePropGroupFinal2,
    ExtractPropGroup0,
    ExtractPropGroup1,
    ExtractPropGroup2,
    ExtractPropGroup3,
    SolveProp,
    SolvePropCarry,
    SolveQuotient,
    SolveQuotientPos1,
    IfPos1FalseZeroed,
    IfPos1FalseZeroedMsgCarry1,
    ShiftLeftByCarryPos0Msg,
    ShiftLeftByCarryPos0MsgNext,
    ShiftRightByCarryPos0Msg,
    ShiftRightByCarryPos0MsgNext,
    IfPos0TrueZeroed,
    IfPos0FalseZeroed,
    IfPos1TrueZeroed,
}

impl Lut1Type {
    /// Returns the string name associated with this LUT type.
    pub fn name(&self) -> &'static str {
        match self {
            Lut1Type::None => "None",
            Lut1Type::MsgOnly => "MsgOnly",
            Lut1Type::CarryOnly => "CarryOnly",
            Lut1Type::CarryInMsg => "CarryInMsg",
            Lut1Type::MultCarryMsg => "MultCarryMsg",
            Lut1Type::MultCarryMsgLsb => "MultCarryMsgLsb",
            Lut1Type::MultCarryMsgMsb => "MultCarryMsgMsb",
            Lut1Type::BwAnd => "BwAnd",
            Lut1Type::BwOr => "BwOr",
            Lut1Type::BwXor => "BwXor",
            Lut1Type::CmpSign => "CmpSign",
            Lut1Type::CmpReduce => "CmpReduce",
            Lut1Type::CmpGt => "CmpGt",
            Lut1Type::CmpGte => "CmpGte",
            Lut1Type::CmpLt => "CmpLt",
            Lut1Type::CmpLte => "CmpLte",
            Lut1Type::CmpEq => "CmpEq",
            Lut1Type::CmpNeq => "CmpNeq",
            Lut1Type::ReduceCarry2 => "ReduceCarry2",
            Lut1Type::ReduceCarry3 => "ReduceCarry3",
            Lut1Type::ReduceCarryPad => "ReduceCarryPad",
            Lut1Type::GenPropAdd => "GenPropAdd",
            Lut1Type::IfTrueZeroed => "IfTrueZeroed",
            Lut1Type::IfFalseZeroed => "IfFalseZeroed",
            Lut1Type::Ripple2GenProp => "Ripple2GenProp",
            Lut1Type::CmpGtMrg => "CmpGtMrg",
            Lut1Type::CmpGteMrg => "CmpGteMrg",
            Lut1Type::CmpLtMrg => "CmpLtMrg",
            Lut1Type::CmpLteMrg => "CmpLteMrg",
            Lut1Type::CmpEqMrg => "CmpEqMrg",
            Lut1Type::CmpNeqMrg => "CmpNeqMrg",
            Lut1Type::IsSome => "IsSome",
            Lut1Type::CarryIsSome => "CarryIsSome",
            Lut1Type::CarryIsNone => "CarryIsNone",
            Lut1Type::MultCarryMsgIsSome => "MultCarryMsgIsSome",
            Lut1Type::MultCarryMsgMsbIsSome => "MultCarryMsgMsbIsSome",
            Lut1Type::IsNull => "IsNull",
            Lut1Type::IsNullPos1 => "IsNullPos1",
            Lut1Type::NotNull => "NotNull",
            Lut1Type::MsgNotNull => "MsgNotNull",
            Lut1Type::MsgNotNullPos1 => "MsgNotNullPos1",
            Lut1Type::SolvePropGroupFinal0 => "SolvePropGroupFinal0",
            Lut1Type::SolvePropGroupFinal1 => "SolvePropGroupFinal1",
            Lut1Type::SolvePropGroupFinal2 => "SolvePropGroupFinal2",
            Lut1Type::ExtractPropGroup0 => "ExtractPropGroup0",
            Lut1Type::ExtractPropGroup1 => "ExtractPropGroup1",
            Lut1Type::ExtractPropGroup2 => "ExtractPropGroup2",
            Lut1Type::ExtractPropGroup3 => "ExtractPropGroup3",
            Lut1Type::SolveProp => "SolveProp",
            Lut1Type::SolvePropCarry => "SolvePropCarry",
            Lut1Type::SolveQuotient => "SolveQuotient",
            Lut1Type::SolveQuotientPos1 => "SolveQuotientPos1",
            Lut1Type::IfPos1FalseZeroed => "IfPos1FalseZeroed",
            Lut1Type::IfPos1FalseZeroedMsgCarry1 => "IfPos1FalseZeroedMsgCarry1",
            Lut1Type::ShiftLeftByCarryPos0Msg => "ShiftLeftByCarryPos0Msg",
            Lut1Type::ShiftLeftByCarryPos0MsgNext => "ShiftLeftByCarryPos0MsgNext",
            Lut1Type::ShiftRightByCarryPos0Msg => "ShiftRightByCarryPos0Msg",
            Lut1Type::ShiftRightByCarryPos0MsgNext => "ShiftRightByCarryPos0MsgNext",
            Lut1Type::IfPos0TrueZeroed => "IfPos0TrueZeroed",
            Lut1Type::IfPos0FalseZeroed => "IfPos0FalseZeroed",
            Lut1Type::IfPos1TrueZeroed => "IfPos1TrueZeroed",
        }
    }
}

/// Enumeration of all available LUT2 types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Lut2Type {
    ManyGenProp,
    TestMany2,
    ManyCarryMsg,
    ManyMsgSplitShift1,
    ManyInv1CarryMsg,
    ManyInv2CarryMsg,
    ManyInv3CarryMsg,
    ManyInv4CarryMsg,
    ManyInv5CarryMsg,
    ManyInv6CarryMsg,
    ManyInv7CarryMsg,
    ManyMsgSplit,
    Manym2lPropBit1MsgSplit,
    Manym2lPropBit0MsgSplit,
    Manyl2mPropBit1MsgSplit,
    Manyl2mPropBit0MsgSplit,
}

impl Lut2Type {
    /// Returns the string name associated with this LUT type.
    pub fn name(&self) -> &'static str {
        match self {
            Lut2Type::TestMany2 => "TestMany2",
            Lut2Type::ManyGenProp => "ManyGenProp",
            Lut2Type::ManyCarryMsg => "ManyCarryMsg",
            Lut2Type::ManyMsgSplitShift1 => "ManyMsgSplitShift1",
            Lut2Type::ManyInv1CarryMsg => "ManyInv1CarryMsg",
            Lut2Type::ManyInv2CarryMsg => "ManyInv2CarryMsg",
            Lut2Type::ManyInv3CarryMsg => "ManyInv3CarryMsg",
            Lut2Type::ManyInv4CarryMsg => "ManyInv4CarryMsg",
            Lut2Type::ManyInv5CarryMsg => "ManyInv5CarryMsg",
            Lut2Type::ManyInv6CarryMsg => "ManyInv6CarryMsg",
            Lut2Type::ManyInv7CarryMsg => "ManyInv7CarryMsg",
            Lut2Type::ManyMsgSplit => "ManyMsgSplit",
            Lut2Type::Manym2lPropBit1MsgSplit => "Manym2lPropBit1MsgSplit",
            Lut2Type::Manym2lPropBit0MsgSplit => "Manym2lPropBit0MsgSplit",
            Lut2Type::Manyl2mPropBit1MsgSplit => "Manyl2mPropBit1MsgSplit",
            Lut2Type::Manyl2mPropBit0MsgSplit => "Manyl2mPropBit0MsgSplit",
        }
    }
}
